cmdargs:
  severity: style_problem
  stat: true
  color: true

policies:
  ProhibitAbbreviationOption:
    enabled: true

  ProhibitImplicitScopeVariable:
    enabled: true

  # ProhibitUnusedVariable:
  #   enabled: true
