name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/setup-python@v2

      - name: Install vint
        run: |
          python -m pip install --upgrade pip
          pip install vim-vint

      - uses: actions/checkout@v2

      - name: Lint with vint
        run: vint .
